version: "3.8"
services:
  falcon-db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - "${PERSISTENT_DATA}/mariadb/:/var/lib/mysq"
      - "${LOG_PATH}/mariadb/:/var/log/mysql"
      - ../configs/mariadb/:/etc/mysql
    environment:
      - MARIADB_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log

  falcon-cache:
    image: redis:latest
    restart: unless-stopped
    depends_on:
      - "falcon-db"
    volumes:
      - ${PERSISTENT_DATA}/redis:/data
    command: redis-server --requirepass $${REDIS_HOST_PASSWORD}

  falconpress:
    image: wordpress:php8.1-fpm-alpine
    volumes:
      - ${STATIC_ROOT}:/var/www/html
      - ../configs/z-update-php-mem-limit.ini:/usr/local/etc/php/conf.d/z-update-php-memory-limit.ini
    depends_on:
      - "falcon-db"
      - "falcon-cache"
    environment:
      - WORDPRESS_DB_HOST=falcon-db
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - WORDPRESS_DB_NAME="${MYSQL_DATABASE}"
      - WORDPRESS_DB_USER="${MYSQL_USER}"
      - WORDPRESS_DB_PASSWORD="${MYSQL_PASSWORD}"
      - WORDPRESS_TABLE_PREFIX=kack_
      - |
        WORDPRESS_CONFIG_EXTRA=
        define( 'WP_REDIS_HOST', 'falcon-cache' );
        define( 'WP_REDIS_PORT', 6379 );
        define( 'WP_REDIS_PASSWORD', '$${REDIS_HOST_PASSWORD}' );
    restart: unless-stopped

  falcon-web:
    image: nginx:latest
    depends_on:
      - "falconpress"
      - "falcon-db"
      - "falcon-cache"
    volumes:
      - ../configs/nginx:/etc/nginx/conf.d
      - ${LOG_PATH}/nginx:/var/log/nginx
      - ${STATIC_ROOT}:/var/www/html
    ports:
      - 8080:80
